Repository OPI-PIB/navoica-platform, pull requests merged in 2020-11, with the labels that each got.

#385 MOOC-1537 Fix: add individual event for lang change for lms and cms
  common/static/js/src/lang_edx.js
Labels: javascript

#396 MOOC-1232 Fix: add wcag message screen reader on clear filter and rem…
  conf/locale/en/LC_MESSAGES/underscore.po
  lms/templates/courseware/courses.html
  lms/templates/discovery/facet.underscore
  lms/templates/discovery/facet_option.underscore
Labels: wcag

#377 MOOC-1300 Feat: add wcag accessibility cookie banner
  lms/static/sass/cookie-alert.scss
  lms/templates/header.html
  lms/templates/main.html
Labels: wcag

#383 MOOC-1272 Feat: add wcag custom select options
  lms/static/js/customSelectAccessibility.js
  lms/static/js/main.js
  lms/templates/courseware/courses.html
  lms/templates/dashboard.html
  lms/templates/instructor/instructor_dashboard_2/instructor_dashboard_2.html
  webpack.common.config.js
Labels: javascript, wcag

#384 MOOC-1473 Fix: add fix on register page
  lms/templates/register.html
Labels: javascript

#391 MOOC-1448 Fix: remove border on selects register page
  lms/static/sass/course-list.scss
  lms/templates/register-form.html
Labels: styling

#398 MOOC-1475 Style: fix style twitter icon to rounded
  lms/static/sass/course-list.scss
  lms/templates/footer.html
  lms/templates/login-sidebar.html
Labels: styling

#393 MOOC-1533 Style: add nowrap flex in header navigation
  lms/static/sass/course-list.scss
Labels: styling

#397 MOOC-1454 Style: fix style course card label (new course)
  conf/locale/en/LC_MESSAGES/underscore.po
  lms/static/sass/course-list.scss
  lms/templates/discovery/course_card.underscore
Labels: styling

#400 MOOC-1272 Style: remove custom select until new design for this element
  lms/templates/courseware/courses.html
  lms/templates/dashboard.html
  lms/templates/instructor/instructor_dashboard_2/instructor_dashboard_2.html
  webpack.common.config.js
Labels: styling, wcag

#399 MOOC-1538 Style: remove unused id language-mobile
  lms/templates/header/navbar-language-mobile.html
Labels: styling

#402 MOOC-1300 Fix: add new translation for cookie banner
  conf/locale/en/LC_MESSAGES/mako.po
  lms/static/sass/cookie-alert.scss
Labels: styling, wcag

#414 MOOC-1035 Style: add responsive iframe, object pdf inside html xblock
  lms/static/sass/course-content.scss
Labels: styling

#415 MOOC-1557 Style: add linkedin icon
  conf/locale/en/LC_MESSAGES/mako.po
  lms/static/sass/course-list.scss
  lms/templates/footer.html
  lms/templates/login-sidebar.html
Labels: styling

#416 MOOC-1457 Feat: add found courses count in dashboard and change trans…
  lms/templates/courseware/courses.html
  lms/templates/dashboard.html
Labels: javascript, styling

#418 MOOC-1551 Style: add new style progress bar
  lms/djangoapps/discussion/templates/discussion/discussion_board_fragment.html
  lms/static/sass/course-content.scss
  lms/static/sass/course-list.scss
  lms/templates/courseware/course_navigation.html
  lms/templates/courseware/courseware.html
  lms/templates/courseware/progress.html
  lms/templates/courseware/static_tab.html
  lms/templates/static_pdfbook.html
  lms/templates/staticbook.html
  openedx/features/course_bookmarks/templates/course_bookmarks/course-bookmarks.html
  openedx/features/course_experience/templates/course_experience/course-home-fragment.html
  openedx/features/learner_profile/templates/learner_profile/learner_profile.html
Labels: styling

#420 MOOC-1441 Style: edit margin in faq, login and register page
  lms/static/sass/course-list.scss
  lms/templates/login-sidebar.html
  lms/templates/login.html
  lms/templates/register.html
Labels: styling

#423 MOOC-1604 Style: remove inline style from cookie alert
  lms/templates/dashboard.html
  lms/templates/main.html
Labels: styling

#424 MOOC-1605 Style: fix padding in course navigation button
  lms/djangoapps/discussion/templates/discussion/discussion_board_fragment.html
  lms/static/sass/course-content.scss
  lms/static/sass/course-list.scss
  lms/templates/courseware/course_about.html
  lms/templates/courseware/courseware.html
  lms/templates/courseware/progress.html
  lms/templates/courseware/static_tab.html
  lms/templates/login.html
  lms/templates/register.html
  lms/templates/static_pdfbook.html
  lms/templates/static_templates/accessibility.html
  lms/templates/static_templates/contact.html
  lms/templates/staticbook.html
  openedx/features/course_bookmarks/templates/course_bookmarks/course-bookmarks.html
  openedx/features/course_experience/templates/course_experience/course-home-fragment.html
  openedx/features/learner_profile/templates/learner_profile/learner_profile.html
Labels: styling
