Repository OPI-PIB/navoica-platform, pull requests merged in 2021-01, with the labels that each got.

#446 MOOC-1298 Style: change wcag in social icon
  conf/locale/en/LC_MESSAGES/mako.po
  lms/templates/footer.html
  lms/templates/header/header.html
  lms/templates/login-sidebar.html
Labels: wcag

#447 MOOC-1552 Feat: add 404 page new look with wcag fixes
  lms/static/images/404.png
  lms/static/sass/course-list.scss
  lms/templates/static_templates/404.html
Labels: styling, wcag

#448 MOOC-1587 Feat: add new continue register enroll course layout
  conf/locale/en/LC_MESSAGES/mako.po
  conf/locale/en_US/LC_MESSAGES/mako.po
  lms/static/images/continue-registration-image.svg
  lms/static/sass/course-list.scss
  lms/templates/courseware/enroll_redirect.html
  lms/templates/header/header.html
Labels: styling
