Repository OPI-PIB/navoica-platform, pull requests merged in 2021-05, with the labels that each got.

#549 MOOC-1901 Style: add new style to password reset email
  common/djangoapps/student/forms.py
  conf/locale/en/LC_MESSAGES/django-partial.po
  lms/djangoapps/student_account/views.py
  lms/templates/registration/password_reset_email.html
Labels: help wanted, styling

#552 MOOC-2087 Feat: add confirm email input to register form
  conf/locale/en/LC_MESSAGES/mako.po
  lms/static/js/tooltip_show.js
  lms/templates/register-form.html
  lms/templates/register.html
Labels: javascript

#559 MOOC-2090 Style: fix the invisible My account icon
  lms/templates/header/user_dropdown.html
Labels: styling
