Repository OPI-PIB/navoica-platform, pull requests merged in 2021-04, with the labels that each got.

#517 Feature/mooc 1510a
  lms/djangoapps/discussion/static/discussion/templates/search.underscore
  lms/djangoapps/discussion/templates/discussion/discussion_board_fragment.html
  lms/envs/common.py
  lms/static/lms/js/require-config.js
  lms/static/sass/course-content.scss
  lms/static/sass/course-list.scss
  lms/static/sass/discussion/_discussion.scss
  lms/static/sass/discussion/elements/_navigation.scss
  lms/static/sass/faq.scss
  lms/static/sass/instructor/common/_forms.scss
  lms/static/sass/login.scss
  lms/static/sass/what-input/_html.scss
  lms/static/sass/what-input/_mixins.scss
  lms/static/sass/what-input/index.scss
  lms/templates/course.html
  lms/templates/courseware/course_navigation.html
  lms/templates/courseware/courses.html
  lms/templates/courseware/courseware.html
  lms/templates/dashboard.html
  lms/templates/dashboard/_dashboard_course_listing.html
  lms/templates/discovery/course_card.underscore
  lms/templates/discovery/filter_bar.underscore
  lms/templates/discussion/_filter_dropdown.html
  lms/templates/fields/field_dropdown_account.underscore
  lms/templates/fields/field_link_account.underscore
  lms/templates/fields/field_text_account.underscore
  lms/templates/footer.html
  lms/templates/forgot_password_modal.html
  lms/templates/header/header.html
  lms/templates/instructor/instructor_dashboard_2/cohorts.underscore
  lms/templates/instructor/instructor_dashboard_2/discussions.underscore
  lms/templates/instructor/instructor_dashboard_2/instructor_dashboard_2.html
  lms/templates/instructor/instructor_dashboard_2/membership-list-widget.underscore
  lms/templates/instructor/instructor_dashboard_2/membership.html
  lms/templates/instructor/instructor_dashboard_2/student_admin.html
  lms/templates/login.html
  lms/templates/preview_menu.html
  lms/templates/register-form.html
  lms/templates/register.html
  lms/templates/seq_module.html
  lms/templates/staff_problem_info.html
  openedx/features/course_experience/templates/course_experience/course-home-fragment.html
  openedx/features/course_experience/templates/course_experience/course-outline-fragment.html
  openedx/features/course_search/templates/course_search/course-search-fragment.html
  package-lock.json
  package.json
  pavelib/assets.py
Labels: styling, wcag

#521 MOOC-1898 Feat: add new footer and navbar header
  common/lib/xmodule/xmodule/js/src/sequence/display.js
  conf/locale/en/LC_MESSAGES/mako.po
  lms/djangoapps/branding/api.py
  lms/envs/common.py
  lms/static/images/my-account-icon.png
  lms/static/images/patrons/logo_en_fmn_grey.png
  lms/static/images/patrons/logo_en_krasp_grey.png
  lms/static/images/patrons/logo_en_men_grey.png
  lms/static/images/patrons/logo_en_opi_pib_grey.png
  lms/static/images/patrons/logo_fmn_grey.png
  lms/static/images/patrons/logo_krasp_grey.png
  lms/static/images/patrons/logo_men_grey.png
  lms/static/images/patrons/logo_opi_pib_grey.png
  lms/static/sass/course-list.scss
  lms/static/sass/footer.scss
  lms/templates/footer.html
  lms/templates/header/header.html
  lms/templates/header/navbar-authenticated.html
  lms/templates/header/navbar-language-desktop.html
  lms/templates/header/navbar-not-authenticated.html
  lms/templates/header/user_dropdown.html
Labels: styling

#522 MOOC-1897 Feat: add new homepage view
  conf/locale/en/LC_MESSAGES/mako.po
  lms/static/images/about-navoica-image.png
  lms/static/images/book-icon.svg
  lms/static/images/certificate-navoica.png
  lms/static/images/certyfikat_Anna_Kowalska_fin.png
  lms/static/images/double-arrow-right-blue.svg
  lms/static/images/double-arrow-right.svg
  lms/static/images/education-navoica.png
  lms/static/images/laptop-icon.svg
  lms/static/images/navoica-homepage-before-1.svg
  lms/static/images/navoica-homepage-before-2.svg
  lms/static/images/navoica-homepage-before-3.svg
  lms/static/images/navoica-homepage-before.svg
  lms/static/images/navoica-homepage-bg-1.svg
  lms/static/images/navoica-homepage-bg-2.png
  lms/static/images/navoica-homepage-bg-hero-tablet.svg
  lms/static/images/partners/Akademia-Sztuki-Wojennej.png
  lms/static/images/partners/Politechnika-Krakowska.png
  lms/static/images/partners/Zachodniopomorski-Uniwersytet-Technologiczny-w-Szczecinie.png
  lms/static/images/partners/centrum-nauki-kopernik.png
  lms/static/images/partners/politechnika-gdanska.png
  lms/static/images/partners/politechnika-lodzka.png
  lms/static/images/partners/politechnika-warszawska.png
  lms/static/images/partners/uam.png
  lms/static/images/partners/warszawski-instytut-bankowosci.png
  lms/static/images/partners/wat.png
  lms/static/images/student-icon.svg
  lms/static/sass/course-list.scss
  lms/templates/course.html
  lms/templates/courses_list.html
  lms/templates/index.html
  lms/templates/main.html
Labels: javascript, styling

#530 MOOC-1748 Fix: add fixex style to login and registration page
  lms/static/sass/course-list.scss
  lms/static/sass/login.scss
Labels: bug, styling

#532 MOOC-2019 Fix: add change styles homepage and navbar
  lms/static/images/my-account-icon-default.png
  lms/static/images/my-account-icon-hover.png
  lms/static/sass/course-list.scss
  lms/templates/header/header.html
  lms/templates/header/navbar-language-desktop.html
  lms/templates/header/navbar-not-authenticated.html
  lms/templates/header/user_dropdown.html
  lms/templates/index.html
Labels: javascript, styling

#538 MOOC-2019 Fix: update fixes new homepage and navbar
  lms/static/sass/course-list.scss
  lms/static/sass/footer.scss
  lms/templates/footer.html
  lms/templates/header/navbar-not-authenticated.html
Labels: styling

#542 MOOC-1927 Style: add tooltip to progress bar
  conf/locale/en/LC_MESSAGES/mako.po
  lms/envs/common.py
  lms/static/js/tooltip_show.js
  lms/static/sass/course-content.scss
  lms/static/sass/course-list.scss
  lms/templates/courseware/course_navigation.html
Labels: javascript, styling, wcag

#545 MOOC-1991 Fix add uppercase to email in registration
  lms/templates/register.html
Labels: javascript

#544 MOOC-1926 Style: add text/style to progress tab
  conf/locale/en/LC_MESSAGES/mako.po
  lms/static/sass/course-list.scss
  lms/templates/courseware/progress.html
Labels: styling
