Repository OPI-PIB/navoica-platform, pull requests merged in 2021-02, with the labels that each got.

#463 MOOC-1682 Style: add responsive header navbar for WCAG accessibility
  lms/static/js/ferie_bez_nudy.js
  lms/static/sass/course-list.scss
  lms/templates/header/header.html
Labels: styling, wcag

#467 MOOC-1741 Feat: add sorting courses by enrollment_start
  lms/static/js/discovery/models/course_discovery.js
  lms/templates/courseware/courses.html
Labels: javascript

#464 MOOC-1553 500/404 h1 fixes
  conf/locale/en/LC_MESSAGES/mako.po
  lms/static/sass/course-list.scss
  lms/templates/static_templates/404.html
  lms/templates/static_templates/server-error.html
Labels: styling, wcag

#462 MOOC-1629 Style: implement new login page design
  common/djangoapps/student/views/login.py
  common/djangoapps/student/views/management.py
  conf/locale/en/LC_MESSAGES/django-partial.po
  conf/locale/en/LC_MESSAGES/mako.po
  lms/static/images/check-solid.svg
  lms/static/images/undraw_Mail_sent_re_0ofv.svg
  lms/static/js/toggle_login_modal.js
  lms/static/sass/course-list.scss
  lms/static/sass/login.scss
  lms/templates/forgot_password_modal.html
  lms/templates/login.html
  lms/templates/register-form.html
  lms/templates/register.html
  lms/templates/registration/password_reset_done.html
Labels: javascript, styling, wcag

#482 MOOC-1816 Fix: add fixes register style and focus email after redirec…
  lms/static/sass/login.scss
  lms/templates/login.html
Labels: styling

#468 MOOC-1758 Style: add new style video xblock inside edit modal
  cms/static/sass/elements/_xblocks.scss
Labels: styling

#479 MOOC-1768 Style: add new style for authorization oauth view
  conf/locale/en/LC_MESSAGES/mako.po
  lms/templates/courseware/enroll_redirect.html
  lms/templates/provider/authorize.html
Labels: styling

#486 MOOC-1819 Fix: add fixed styles forgotten password and scroll to erro…
  lms/static/sass/login.scss
  lms/templates/forgot_password_modal.html
  lms/templates/login.html
  lms/templates/register-form.html
  lms/templates/register.html
Labels: styling

#493 MOOC-1843 Fix: add fixes WCAG login/register page
  lms/templates/forgot_password_modal.html
  lms/templates/login.html
  lms/templates/register-form.html
  lms/templates/register.html
Labels: wcag
